import type { Metadata } from "next";
import { Suspense } from "react";
import Script from "next/script";
import './globals.css';
import ThemeToggle from "@/components/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInitScript = `
    (function () {
      try {
        var savedTheme = localStorage.getItem('theme');
        var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        var shouldUseDark = savedTheme === 'dark' || ((savedTheme === 'system' || !savedTheme) && prefersDark);
        if (shouldUseDark) {
          document.documentElement.classList.add('dark');
          document.documentElement.style.colorScheme = 'dark';
        } else {
          document.documentElement.classList.remove('dark');
          document.documentElement.style.colorScheme = 'light';
        }
      } catch (e) {}
    })();
  `;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
      </head>
      <body className="antialiased">
        <Suspense fallback={null}>
          <ThemeToggle />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
